# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160816_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Berbat'), (2, 'Kötü'), (3, 'Meh'), (4, 'Güzel'), (5, 'Yıkılıyooo')], default=3),
        ),
    ]
