# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_auto_20160818_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
