# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20160822_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pin_pic',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='blue', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='coffee', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Category'),
        ),
    ]
